import React from 'react'
import type { Checklist } from '@/shared/config'
import { computeProgress } from '@/shared/lib'
import styles from './ChecklistReport.module.css'

const CHECK_ICON = '\u2713'
const SKIP_ICON = '\u2013'
const PENDING_ICON = '\u25CB'

export interface ChecklistReportLabels {
  active: string
  completed: string
  progress: string
  fromTemplate: string
  generatedBy: string
  noItems: string
  noCategories: string
  comment?: string
}

interface ChecklistReportProps {
  checklist: Checklist
  language?: string
  labels?: Partial<ChecklistReportLabels>
  comment?: string
}

const DEFAULT_LABELS: ChecklistReportLabels = {
  active: 'Active',
  completed: 'Completed',
  progress: 'Progress',
  fromTemplate: 'From template',
  generatedBy: 'Generated by Moirai',
  noItems: 'No items',
  noCategories: 'No categories',
}

export const ChecklistReport: React.FC<ChecklistReportProps> = ({ checklist, language = 'en', labels: labelsProp, comment }) => {
  const labels = { ...DEFAULT_LABELS, ...labelsProp }

  const progress = computeProgress(checklist)
  const totalItems = checklist.categories.reduce((acc, c) => acc + c.items.length, 0)
  const processedItems = totalItems > 0 ? Math.round((progress / 100) * totalItems) : 0
  const statusLabel = checklist.status === 'completed' ? labels.completed : labels.active

  const locale =
    language === 'lv' ? 'lv-LV' :
    language === 'ru' ? 'ru-RU' :
    language === 'lt' ? 'lt-LT' :
    language === 'et' ? 'et-EE' : 'en-US'

  const date = new Date(checklist.createdAt).toLocaleDateString(locale, {
    year: 'numeric', month: 'short', day: 'numeric',
  })

  return (
    <div className={styles.report}>
      <div className={styles.headerBand}>
        <h1 className={styles.title}>{checklist.title}</h1>
        <div className={styles.meta}>
          <span className={styles.statusBadge}>{statusLabel}</span>
          <span>{date}</span>
        </div>
        {checklist.templateTitle && (
          <p className={styles.templateSource}>{labels.fromTemplate}: {checklist.templateTitle}</p>
        )}
        <div className={styles.accentLine} />
      </div>

      <div className={styles.content}>
        <div className={styles.progressSection}>
          <div className={styles.progressHeader}>
            <span className={styles.progressLabel}>{labels.progress}</span>
            <div>
              <span className={styles.progressValue}>{progress}%</span>
              {' '}
              <span className={styles.progressMeta}>{processedItems}/{totalItems}</span>
            </div>
          </div>
          <div className={styles.progressTrack}>
            <div className={styles.progressFill} style={{ width: `${progress}%` }} />
          </div>
        </div>

        {comment && (
          <div className={styles.commentSection}>
            {labels.comment && <p className={styles.commentLabel}>{labels.comment}</p>}
            <p className={styles.commentText}>{comment}</p>
          </div>
        )}

        {checklist.categories.length === 0 ? (
          <p className={styles.empty}>{labels.noCategories}</p>
        ) : (
          checklist.categories.map(cat => (
            <section key={cat.id} className={styles.category}>
              {!cat.unwrapped && (
                <div className={styles.catHeader}>
                  <h2 className={styles.catName}>{cat.name}</h2>
                </div>
              )}
              <div className={styles.catBody}>
                {cat.items.length === 0 ? (
                  <p className={styles.empty}>{labels.noItems}</p>
                ) : (
                  <ul className={styles.items}>
                    {cat.items.map(item => {
                      const statusClass = item.checked
                        ? styles.itemChecked
                        : item.skipped
                          ? styles.itemSkipped
                          : styles.itemPending
                      const icon = item.checked
                        ? CHECK_ICON
                        : item.skipped
                          ? SKIP_ICON
                          : PENDING_ICON
                      const itemComments = item.comments || []
                      return (
                        <li key={item.id} className={`${styles.item} ${statusClass}`}>
                          <span className={styles.itemIcon}>{icon}</span>
                          <div className={styles.itemContent}>
                            <span className={styles.itemText}>{item.text}</span>
                            {item.description && (
                              <p className={styles.itemDesc}>{item.description}</p>
                            )}
                            {itemComments.length > 0 && (
                              <div className={styles.itemComments}>
                                {itemComments.map(c => (
                                  <div key={c.id} className={styles.itemComment}>
                                    <p className={styles.itemCommentText}>{c.text}</p>
                                    <span className={styles.itemCommentDate}>
                                      {new Date(c.createdAt).toLocaleDateString(locale, { month: 'short', day: 'numeric' })}
                                    </span>
                                  </div>
                                ))}
                              </div>
                            )}
                          </div>
                        </li>
                      )
                    })}
                  </ul>
                )}
              </div>
            </section>
          ))
        )}

        <footer className={styles.footer}>
          {labels.generatedBy} &bull; {date}
        </footer>
      </div>
    </div>
  )
}
